//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallTransactionMaster
    {
        public int CTId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SalesAssociateName { get; set; }
        public int TotalNumberOfCall { get; set; }
        public int TotalQualityOfCall { get; set; }
        public int TotalGoogleMeetCall { get; set; }
        public decimal RevenueGenerate { get; set; }
        public decimal TotalTalkTime { get; set; }
        public string InsertedBy { get; set; }
    }
}
