//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignMaster
    {
        public int CId { get; set; }
        public string LinkedInUser { get; set; }
        public string CampaignCode { get; set; }
        public string Message { get; set; }
    }
}
