//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTimeLine
    {
        public int TimeLineId { get; set; }
        public int RefCandidateId { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual CandidateMaster CandidateMaster { get; set; }
        public virtual UserAccountDetail UserAccountDetail { get; set; }
    }
}
