//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAssign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateAssign()
        {
            this.SubmissionDetails = new HashSet<SubmissionDetail>();
        }
    
        public int AssignedId { get; set; }
        public int RefTeamId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public int refMarketingId { get; set; }
    
        public virtual CandidateMarketingDetail CandidateMarketingDetail { get; set; }
        public virtual TeamDetail TeamDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionDetail> SubmissionDetails { get; set; }
    }
}
