//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMarketingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateMarketingDetail()
        {
            this.CandidateAssigns = new HashSet<CandidateAssign>();
        }
    
        public int MarketingId { get; set; }
        public int RefCandidateId { get; set; }
        public string MarketingEmailId { get; set; }
        public string MarketingContactNumber { get; set; }
        public string OriginalResume { get; set; }
        public string MarketingResume { get; set; }
        public string InsertedBy { get; set; }
        public string OtherRemarks { get; set; }
        public string MarketingStatus { get; set; }
        public bool LocationConcern { get; set; }
        public string RequiredLocationList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAssign> CandidateAssigns { get; set; }
        public virtual CandidateMaster CandidateMaster { get; set; }
    }
}
