//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMaster
    {
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmailId { get; set; }
        public string CandidateMarketingEmailId { get; set; }
        public string CandidatePersonalNumber { get; set; }
        public string CandidateMarketingNumber { get; set; }
        public string InsertedBy { get; set; }
        public string TechnologyName { get; set; }
        public string VisaStatus { get; set; }
        public string AssignTo { get; set; }
        public string OtherDetails { get; set; }
        public string Status { get; set; }
    }
}
