//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientMaster()
        {
            this.RecuringMasters = new HashSet<RecuringMaster>();
            this.RecurringMasters = new HashSet<RecurringMaster>();
        }
    
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientEmaiId { get; set; }
        public string BranchName { get; set; }
        public int RefServiceId { get; set; }
        public int RefRecurringId { get; set; }
        public int RefTechnologyId { get; set; }
        public int SalesAssociateName { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Paid { get; set; }
        public System.DateTime EnteryDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    
        public virtual RecurringType RecurringType { get; set; }
        public virtual ServiceSale ServiceSale { get; set; }
        public virtual TechnologyMaster TechnologyMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecuringMaster> RecuringMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringMaster> RecurringMasters { get; set; }
    }
}
