//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dashReportingEntities : DbContext
    {
        public dashReportingEntities()
            : base("name=dashReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallTransactionMaster> CallTransactionMasters { get; set; }
        public virtual DbSet<CampaignMaster> CampaignMasters { get; set; }
        public virtual DbSet<CandidateMaster> CandidateMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<JobPortalMaster> JobPortalMasters { get; set; }
        public virtual DbSet<LinkedInMaster> LinkedInMasters { get; set; }
        public virtual DbSet<RecuringMaster> RecuringMasters { get; set; }
        public virtual DbSet<RecurringMaster> RecurringMasters { get; set; }
        public virtual DbSet<RecurringType> RecurringTypes { get; set; }
        public virtual DbSet<ReportSubmissionDetail> ReportSubmissionDetails { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<SalesKIPMaster> SalesKIPMasters { get; set; }
        public virtual DbSet<SalesKPIMaster> SalesKPIMasters { get; set; }
        public virtual DbSet<ServiceSale> ServiceSales { get; set; }
        public virtual DbSet<SubmissionMaster> SubmissionMasters { get; set; }
        public virtual DbSet<TeamMaster> TeamMasters { get; set; }
        public virtual DbSet<TechnologyMaster> TechnologyMasters { get; set; }
        public virtual DbSet<UlincMaster> UlincMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<VisaMaster> VisaMasters { get; set; }
    }
}
