//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInMaster
    {
        public int LId { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public string LeadBy { get; set; }
        public string LeadType { get; set; }
        public string LinkedInUrl { get; set; }
        public string CandidateName { get; set; }
        public string CandidateNumber { get; set; }
        public string LinkedInEmailid { get; set; }
        public string CandidateLocation { get; set; }
        public string TechnologyName { get; set; }
        public string AssignedToSalesAssociate { get; set; }
        public string Remarks { get; set; }
        public string Feedback { get; set; }
    }
}
