//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringMaster
    {
        public int PaymentId { get; set; }
        public int RefClientId { get; set; }
        public decimal Payment { get; set; }
        public string ReceivedIn { get; set; }
        public bool SentEmailReminder { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
