//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecurringType()
        {
            this.CandidateMasters = new HashSet<CandidateMaster>();
        }
    
        public int RecurringTypeId { get; set; }
        public string RecurringTitle { get; set; }
        public decimal Amount { get; set; }
        public int Installment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateMaster> CandidateMasters { get; set; }
    }
}
