//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSubmissionDetail
    {
        public int ReportSId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CandidateName { get; set; }
        public string TeamLeadName { get; set; }
        public string RecruiterName { get; set; }
        public string Technology { get; set; }
        public string VisaStatus { get; set; }
        public string CandidateEmailId { get; set; }
        public string CandidateMobileNumber { get; set; }
        public int TotalSubmission { get; set; }
        public int TotalInterview { get; set; }
    }
}
