//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesKIPMaster
    {
        public int Id { get; set; }
        public int DailyCalls { get; set; }
        public int DailyQualityCalls { get; set; }
        public int QualityCallMin { get; set; }
        public int AverageCallMin { get; set; }
        public decimal TargetedRevenue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool CurrentKPI { get; set; }
    }
}
