//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskMaster
    {
        public int TaskId { get; set; }
        public Nullable<int> TaskTitleId { get; set; }
        public string TaskDetails { get; set; }
        public string AssignBy { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.TimeSpan> AssignTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Feedback { get; set; }
    }
}
