//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMaster
    {
        public int TeamId { get; set; }
        public string MemberName { get; set; }
        public string TeamLeadName { get; set; }
        public string ManagerName { get; set; }
    }
}
