//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamDetail()
        {
            this.CandidateAssigns = new HashSet<CandidateAssign>();
        }
    
        public int TeamId { get; set; }
        public int Member { get; set; }
        public int TeamLead { get; set; }
        public int TeamManager { get; set; }
        public string Department { get; set; }
    
        public virtual UserAccountDetail UserAccountDetail { get; set; }
        public virtual UserAccountDetail UserAccountDetail1 { get; set; }
        public virtual UserAccountDetail UserAccountDetail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAssign> CandidateAssigns { get; set; }
    }
}
