//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UlincMaster
    {
        public int UId { get; set; }
        public System.DateTime Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string LinkedInUrl { get; set; }
        public string ForwaredToSalesAssociate { get; set; }
        public string LinkedInUser { get; set; }
        public string CampaignCode { get; set; }
        public string TimeForCall { get; set; }
        public string Feedback { get; set; }
        public bool RequestAccepted { get; set; }
        public bool IsPositive { get; set; }
    }
}
