//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.ClientMasters = new HashSet<ClientMaster>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string RocketName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string UserImageUrl { get; set; }
        public string UserBranch { get; set; }
        public int RefRoleId { get; set; }
        public bool IsLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMaster> ClientMasters { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
